### ISSUE TITLE
magic number 5800000c etc

### ISSUE THREAD

**Issue by laoshaw** [soundpaint/rp2040pio#6]
where is the address 58000014 etc coming from at https://rp2040pio-docs.readthedocs.io/en/latest/io.html

I looked up all memory mapped addresses from datasheet etc and could not figure out why the emulator is waiting on those addresses.

**Comment by soundpaint** [comment]
58000014:
https://rp2040pio-docs.readthedocs.io/en/latest/pico-emu-registers.html#wallclock-lsb-details-label

5800000C:
https://rp2040pio-docs.readthedocs.io/en/latest/pico-emu-registers.html#masterclk-trigger-phase0-details-label
